spring:
  profiles:
    active: local
  application:
    name: mds
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
mybatis:
  mapper-locations: classpath*:mapper/customer/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.mds.matrix.customer.model
  type-handlers-package: com.mds.matrix.common.enums.handler