mybatis:
  mapper-locations: classpath*:mapper/customer/*.xml
  type-aliases-package: com.mds.matrix.customer.model

sharding:
  jdbc:
    datasource:
      ds_0:
        jdbc-url: jdbc:mysql://localhost:3306/maidushi
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: cmx123
        minimum-idle: 10
        maximum-pool-size: 200
        connection-timeout: 30000
        connection-test-query: select 1
        max-lifetime: 600000
        idle-timeout: 120000